In [1]:
import numpy as np
import pandas as pd
import polars as pl
pldf = pl.scan_csv('/work/Users/sammy/Documents/Sammy_DS/Multiple Linear Regression/50_Startups.csv')
pddf = pd.read_csv('/work/Users/sammy/Documents/Sammy_DS/Multiple Linear Regression/50_Startups.csv')

In [2]:
pldf = pl.scan_csv('/work/Users/sammy/Documents/Sammy_DS/Multiple Linear Regression/50_Startups.csv')
pddf = pd.read_csv('/work/Users/sammy/Documents/Sammy_DS/Multiple Linear Regression/50_Startups.csv')

In [3]:
pldf.fetch(5)

shape: (5, 5)
┌───────────┬────────────────┬─────────────────┬────────────┬───────────┐
│ R&D Spend ┆ Administration ┆ Marketing Spend ┆ State      ┆ Profit    │
│ ---       ┆ ---            ┆ ---             ┆ ---        ┆ ---       │
│ f64       ┆ f64            ┆ f64             ┆ str        ┆ f64       │
╞═══════════╪════════════════╪═════════════════╪════════════╪═══════════╡
│ 165349.2  ┆ 136897.8       ┆ 471784.1        ┆ New York   ┆ 192261.83 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 162597.7  ┆ 151377.59      ┆ 443898.53       ┆ California ┆ 191792.06 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 153441.51 ┆ 101145.55      ┆ 407934.54       ┆ Florida    ┆ 191050.39 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 144372.41 ┆ 118671.85      ┆ 383199.62       ┆ New York   ┆ 182901.99 │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 142107.34 ┆ 91391.77       ┆ 366168.42       ┆ Florida    ┆ 166187.94 │
└───────────┴────────────────┴─────────────────┴────────────┴───────────┘

In [4]:
y = pldf.select(pl.col('Profit'))

In [5]:
pldf.schema

{'R&D Spend': polars.datatypes.Float64,
 'Administration': polars.datatypes.Float64,
 'Marketing Spend': polars.datatypes.Float64,
 'State': polars.datatypes.Utf8,
 'Profit': polars.datatypes.Float64}

In [6]:
X = pldf.select(pl.exclude('Profit'))

In [7]:
X.fetch(3)

shape: (3, 4)
┌───────────┬────────────────┬─────────────────┬────────────┐
│ R&D Spend ┆ Administration ┆ Marketing Spend ┆ State      │
│ ---       ┆ ---            ┆ ---             ┆ ---        │
│ f64       ┆ f64            ┆ f64             ┆ str        │
╞═══════════╪════════════════╪═════════════════╪════════════╡
│ 165349.2  ┆ 136897.8       ┆ 471784.1        ┆ New York   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 162597.7  ┆ 151377.59      ┆ 443898.53       ┆ California │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 153441.51 ┆ 101145.55      ┆ 407934.54       ┆ Florida    │
└───────────┴────────────────┴─────────────────┴────────────┘

In [8]:
X = np.array(X.collect().to_pandas())
y = np.array(y.collect().to_pandas())

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer([('encoder', OneHotEncoder(), [-1])], remainder = 'passthrough')
transformer.fit(X)
X = transformer.transform(X)

In [9]:
X

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
scaler = StandardScaler()
scaler.fit(X_train[:, -3:])
X_train[:, -3:] = scaler.transform(X_train[:, -3:])
X_test[:, -3:] = scaler.transform(X_test[:, -3:])

In [14]:
X_test

array([[0.0, 1.0, 0.0, -0.12149520306216502, 2.2889053032012234,
        -0.6803228661410794],
       [1.0, 0.0, 0.0, 0.6280306007656555, -1.2206949887864658,
        0.38557773677354845],
       [0.0, 1.0, 0.0, 0.6549006077802048, -0.49434194923946795,
        0.21885524294941494],
       [0.0, 1.0, 0.0, -0.947621483893497, -1.494179356244993,
        -0.30512103616996794],
       [0.0, 1.0, 0.0, 1.770481112122021, -0.8593266741758989,
        1.666880795073106],
       [0.0, 0.0, 1.0, 0.009617753042540427, 0.17279111579172604,
        1.2234122937277723],
       [0.0, 0.0, 1.0, -1.1135310904221214, -2.218961756571209,
        -0.13669119113063422],
       [0.0, 0.0, 1.0, -0.22790702970059823, 1.1322241571857976,
        -0.922748838200462],
       [0.0, 1.0, 0.0, 0.0504700706558041, -0.023511746780132174,
        0.819520742715403],
       [0.0, 1.0, 0.0, 1.5250985323520592, -1.2361016229924873,
        1.3285846911963288]], dtype=object)

In [15]:
X_train

array([[0.0, 1.0, 0.0, -0.3500645436227844, -0.7854710924793271,
        0.1011968019362538],
       [0.0, 0.0, 1.0, -0.555303187426314, -1.481174262628151,
        0.02734979174277092],
       [0.0, 1.0, 0.0, 0.07935762307586282, 0.8013338146656704,
        -0.551521323997471],
       [1.0, 0.0, 0.0, -0.5463823849331263, 1.3250581707161837,
        0.07011683779235604],
       [0.0, 1.0, 0.0, 0.4348537132854595, -0.3559866348200946,
        0.7514851578736048],
       [0.0, 1.0, 0.0, 1.2694314288195354, 0.855185185174973,
        0.986031184474382],
       [0.0, 1.0, 0.0, 1.045250070905001, 1.2807704710942711,
        0.44039999942558483],
       [0.0, 0.0, 1.0, -1.529843000700978, 0.029420649133439825,
        -1.6218751012780783],
       [0.0, 0.0, 1.0, -1.5397625087372082, -2.767672641730695,
        -1.6372965026688253],
       [0.0, 0.0, 1.0, -0.13115188245559178, 1.144977005989267,
        -0.7694999122824163],
       [0.0, 0.0, 1.0, 0.927916133722245, -0.029920619212990152,
   

In [16]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = regressor.predict(X_test)

In [18]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [19]:
y_pred

array([[103015.20159796],
       [132582.27760816],
       [132447.73845174],
       [ 71976.09851258],
       [178537.48221055],
       [116161.24230165],
       [ 67851.69209676],
       [ 98791.73374687],
       [113969.43533012],
       [167921.0656955 ]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=57d5770d-d68f-47c5-bc32-65c81e0e368b' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>